# Generated by Django 5.1.1 on 2025-01-01 12:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='idPelicula',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='puntuaciones',
        ),
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': ('titulo', 'fecha')},
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='fechaEstreno',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='imdbUrl',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='calificacion_critica',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Calificación Crítica'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='calificacion_publico',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Calificación Público'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.TextField(blank=True, null=True, verbose_name='Director'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duración (en minutos)'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='edad',
            field=models.TextField(blank=True, null=True, verbose_name='Edad recomendada'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Estreno'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='guionista',
            field=models.TextField(blank=True, null=True, verbose_name='Guionista'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='productor',
            field=models.TextField(blank=True, null=True, verbose_name='Productor'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(blank=True, null=True, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='idPelicula',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.TextField(verbose_name='Género')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generos', to='main.pelicula')),
            ],
            options={
                'ordering': ('genero',),
            },
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Ocupacion',
        ),
        migrations.DeleteModel(
            name='Puntuacion',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
