# Generated by Django 5.1.1 on 2025-01-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_pelicula_categorias_remove_usuario_ocupacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': []},
        ),
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': []},
        ),
        migrations.AddField(
            model_name='pelicula',
            name='foto',
            field=models.TextField(blank=True, null=True, verbose_name='foto'),
        ),
    ]
